name: GIGA
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.10.4=h7ca028e_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=he1b5a44_3
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.2.0=py38hc5bc63f_1
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py38hff7bd54_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - python=3.8.8=hdb3f193_4
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.35.3=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.2=py38_cu110
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - addict==2.4.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.1
    - catkin-pkg==0.4.23
    - cffi==1.14.5
    - chardet==4.0.0
    - cycler==0.10.0
    - cython==0.29.22
    - dataclasses==0.6
    - decorator==4.4.2
    - defusedxml==0.7.1
    - docutils==0.17
    - entrypoints==0.3
    - freetype-py==2.2.0
    - future==0.18.2
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.36.1
    - idna==2.10
    - imageio==2.9.0
    - ipykernel==5.5.3
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.2
    - notebook==6.3.0
    - numpy==1.20.2
    - oauthlib==3.1.0
    - open3d==0.12.0
    - packaging==20.9
    - pandas==1.2.3
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plyfile==0.7.3
    - prometheus-client==0.10.0
    - prompt-toolkit==3.0.18
    - protobuf==3.15.7
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==2.7.9
    - pycollada==0.6
    - pycparser==2.20
    - pyglet==1.5.15
    - pygments==2.8.1
    - pyopengl==3.1.0
    - pyparsing==2.4.7
    - pyrender==0.1.45
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytorch-ignite==0.4.4
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.18.1
    - scikit-learn==0.24.1
    - scipy==1.6.2
    - send2trash==1.5.0
    - sklearn==0.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.9.4
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2021.3.31
    - torch==1.7.0
    - torch-scatter==2.0.6
    - tornado==6.1
    - tqdm==4.59.0
    - traitlets==5.0.5
    - trimesh==3.9.10
    - urdfpy==0.0.22
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
prefix: /mnt/data2/zhenyu/anaconda3/envs/GIGA
